#**`PYTHON BASICS`**



```
Arrays,Arrays - Interger data type and can be multi dimensional
Tuple,"tuple - similar to list, but created in (), not mutable (Mutable - can be updated/Changed)"
List,"List - similar to tuple, but created in [], mutable. Can have Integer or string, 1Dimentional, nested list can be multi dimensional"
DataFrame,"Series - 1D dataframe is called series, Index of our own type; Dataframe - 2D table, more like SQL table, can have multiple data type data's"
Dictionary,Dictionary - creating data with data and column names will be dictionary. Next step its converted to Dataframe
```


In [ ]:
import pandas as pd
import numpy as np

a1 = (1,2) # Tuple will be in round braces, not mutable - cannot be changed
aa1 = ('a','bb') # tuple can also have strings, similar to list
a2 = [1,2] # List will be in squared braced, mutable. Can have integers and strings

mylist = list['abcdefghijklmnopqrstuvwxyz']
np.arange(6)

list['abcdefghijklmnopqrstuvwxyz']

In [ ]:
fruit = 'apple'
print(fruit)
print(5+4)
print('apple')
fruit[0:4] # 0 to n-1 position in the variable
type(fruit) # str

num=2
type(num) # int

# this is a single line comment

""" multi line comments """

text = input("get input from user")

sentence1  = "she said, \"that's Use backslash to use both types of quotation marks\""
print(sentence1)
sentence2 = 'she said, "that\'s Use backslash to use both thypes of quotation marks"'
print(sentence2)
sentence3 = 'she said, that\'s Use backslash to use both thypes of quotation marks'
print(sentence3)

In [ ]:
animals = ['man','bear','pig']
type(animals)
print(animals.index('bear')) # returns index number 0,1,2 # output = 1
# animals.index('cat') # returns error as cat not found

# exception handling

try:
    cat_index = animals.index('cat')
except:
        cat_index = 'No cat found'
print(cat_index)

In [ ]:
print('I'+'Love'+'python') # string concatenation
print('I'*10) # I printed 10 times
name = 3
print ('I'+str(name))

In [ ]:
print('I {} Python'.format('love')) # Placeholder in print statement
print('I {} {}'.format('love','python'))
print('I {0} {1}, {1} {0}s me'.format('love','python'))
print('{0:8} | {1:8}'.format('apples','oranges')) # this can be used to create tables
print('{0:8} | {1:<8.2f}'.format('apples',2)) #gives 2.00, < is left aligned, .2f is 2 float values

print('               {}'.format('_'*5))
print('               <{}>'.format('santhosh'))

In [ ]:
2**4 # Exponential
4%2
4/2

In [ ]:
# Booleans

bool_1 = True
bool_2 = False

1==2

37> 29 and 37<40

# order of operations
not
and
or

In [ ]:
# Conditional

if 45 > 59:
    print("working")
elif 45 == 45:
    print("elif executing")
else:
    print("else executing")
print("outside if loop")

In [ ]:
# Functions

# DRY concept - Dont repeat yourself

def say_hi():
    print('HI')
say_hi() # call function

help(say_hi)

In [ ]:
# Practice exercise

def user_input():
    text1 = input("enter the first word :")
    return text1
out_text1 = user_input()
print("The capital of india is {} and its not, its union territory".format(out_text1))

In [ ]:
# Practice exercise 2

miles1 = input("How many kms you want to travel ?")
miles = int(miles1)
if miles < 3:
    print("Start walking !")
elif miles < 300:
    print("Drive!")
elif miles >= 300:
    print("fly")
else:
    print('NA')

In [ ]:
# Practice exercise 3

charge = 0.51
print("Charge per day",charge * 24)
print("Charge per month",charge * 24 * 30)

print(918/(charge * 24))

In [ ]:
# List

list_name = ['a','b','c']
# list_name = [] # empty list
list_name[0]
list_name[0] = 'd'
list_name
list_name[-1]

list_name.append('e')
list_name.extend(['x','y'])
ext = ['m','n']
list_name.extend(ext)
list_name

list_name.insert(0,'aa')
list_name.insert(2,'bb')
list_name

list_name[1:2]
list_name[0:2]
list_name[:2]
list_name[-2:] # last two

In [ ]:
# LOOPS

animals = ['man','cat','bear']
for x in animals:
    print(x.upper())

index = 0
while index < len(animals):
    print(animals[index].upper())
    index += 1

In [ ]:
# Sorting & Ranges

for number in range(5):
    print(number)

for number in range(0,5,2):
    print(number)

In [ ]:
list = ['a','b']

for numb in list:
    xx = input("Enter to do list : ")
    list.append(xx)
    print(list)

In [ ]:
# FILES

hosts = open('c:\Log\Messages\sample.txt')
hosts_content = hosts.read() # reads content
seek(offset) # change position to offset

hosts.seek(0) # start of the file
hosts.seek(5) # 5th byte, 5th character
hosts.read(3)
hosts.tell() # current position
hosts.close() # close the file
hosts.closed # says true or false ,whether file closed or open

# to automatically close use with condition

with open(file_path) as hosts:
    print(hosts.read())
print("File automatically closed aafter ending with statement")

with open(path) as hosts:
    for line in hosts:
        print(line) # print line by line, but has 2 line spaces between lines

with open(path) as hosts:
    for line in hosts:
        print(line.rstrip()) # print line by line, but removes line spaces between lines

# File modes

open(path,mode)

r - read(default)
w - write
x - create new file and write
a - write, append to existing data
+ - read & write to same file
b - binary eg: image file, compressed
t - text (default)

with open(path,'w') as hosts:
    hosts.write("santhosh")
    hosts.write("kumar")
    # output - santhoshkumar - printed in same line use \n for new line

In [ ]:
# Practice Exercise

with open('untitled.txt') as hosts:
     hosts.seek(0)
    for line in hosts:
        print(hosts.tell())

# **`LEARNING PANDAS`**

In [ ]:
import pandas as pd
import numpy as np

from sklearn import datasets
dir(datasets)
df = datasets.load_iris()
iris = pd.DataFrame(data=df.data,columns=df.feature_names)
iris.head()
iris['target'] = df.target
iris.dtypes

In [ ]:
# DICTIONARIES

# dic_name = {key1:value1, keyN:valueN} # example name and phone number

contacts = {'santhosh':9788,'priya':98786}
contacts['santhosh']

contacts['yazh'] = 89575
contacts
len(contacts)

del contacts['yazh']


contacts = {'santhosh':[9788,968675],'priya':98786}
print(contacts['santhosh'][0])

if 'santhosh' in contacts.keys():
    print("sucess")


contacts = {'santhosh':9788,'priya':98786}
print(contacts.values( ))
print(98786 in contacts.values())

for contact in contacts:
    print(contacts[contact])

for x,y in contacts:  # x will be assigned with key and Y will be assigned with value from dictionary
    print(x,y)

# NESTED DICTIONARIES

contacts = {'santhosh':{'phone':9788,'email':'sant@xx.com'},
            'priya':{'phone':98786,'email':'priya@xx.com'}}

for contact in contacts:
    print(contacts[contact])
    print(contacts[contact]['phone'])

import pandas as pd
df = pd.DataFrame(contacts)
df

{'phone': 9788, 'email': 'sant@xx.com'}
9788
{'phone': 98786, 'email': 'priya@xx.com'}
98786


santhosh         priya
phone         9788         98786
email  sant@xx.com  priya@xx.com

In [ ]:
arr_1D = np.array([1,2]) # array
arr_1D.shape
arr_2D = np.array([[1,2],[2,3]])
arr_2D.ndim
arr_3D = np.array([[1,2]])
arr_3D.shape

list = [1,2,3,4]
tuple =(1,2,3,4)
dict = {'fruits':['apple','oranges'],
        'price':[100,120]}
type(dict)

ds = pd.Series(dict) # conver dict to series
df = pd.DataFrame(dict) # convert dict to dataframe
dict = df.to_dict() # convert dataframe to dict
df.to_frame() # converts series to dataframe
df.values.tolist() # convert df to list

if dict:
  print("Not empty !")
if list:
  print("Not empty !")
if tuple:
  print("Not empty !")
if not ds.empty: # note the difference here
  print("Not empty !")

Not empty !


In [ ]:
# SQL SELECT (SUBSETTING COLUMNS)
iris.iloc[:,2:4] # filter for column position 2,3 (starts with 0 position)
iris.loc[:,['sepal length (cm)','sepal width (cm)']]
iris.loc[:,['sepal length (cm)']]
iris.loc[:,['sepal length (cm)','target','rank_s1']]
iris.columns.values
iris.columns.get_loc('target') # column location

iris.iat[1,2] # used to filter for single value
iris.iloc[1,2] # same as above, returns single value
iris.at[4,'target'] # returns single value
iris.iat[1:3,4] # error, "AT" can be used to access single values only

iris[['sepal length (cm)','sepal width (cm)','target']] # other ways to select columns
iris['target'] #single column
iris.target #single column
iris.filter(regex='sepal')

dt_type='Bool'
df.loc[:, df.dtypes == dt_type] # filter based on column data types

In [ ]:
# SQL WHERE (SUBSETTING ROWS)
iris.iloc[1:20,] # filter for row number position 1 to 19 (starts with 0) and all columns
iris.iloc[1:20,1] # 19 rows position based, column 1 (position)
iris.loc[1:2,] # filter for index 1,2
iris.iloc[1:2,] # filter for position 1
iris[(iris['sepal length (cm)'] > 5)]
iris[~(iris['sepal length (cm)'] > 5)] # using NOT
iris[(iris['sepal length (cm)'] > 5) & (iris['sepal width (cm)'] > 5)] # using and
iris[(iris['sepal length (cm)'] > 5) | (iris['sepal width (cm)'] > 5)] # using or

val = [0,1]
iris[(iris['target'].isin(val))] # in val
iris[~(iris['target'].isin(val))] # not in val
iris.loc[iris['target']==0,['sepal length (cm)','sepal width (cm)']]
iris.query('target == 0') # query allows boolean expression to filter rows
iris.query('employee_Name.str.startswith("santhosh")',engine='python') # filter for rows
iris.drop_duplicates() # removes duplicate rows, checks across all columns
iris.sample(10) # random sample of 10 rows
iris.sample(frac=0.5) # 50% random sample
iris.nlargest(10,'sepal length (cm)') # select top 10 in descending order based on sepal length. if ties then choose first in order in datset
iris.nlargest(10,'sepal length (cm)', keep='all') # keep ='all' keeps all if ties, keep = last, keeps last in order in dataset
iris.nsmallest(10,'sepal length (cm)')

df.Employee_City[0:1,] # is equal to head(1)"
df.Employee_City[-1:,] # is equal to tail(1)"
df.Employee_City[-2:,] # is equal to tail(2)"
df.iloc[-2:,-2:] - # Last 2 columns and 2 rows"
df.Employee_City[:-1,] # all rows excluding last row

#print 1st, 3rd, 5th row....
df[::3]

In [ ]:
# SQL GROUP BY
iris.groupby('target') # wont throw error, stored as an object, no output
iris.groupby('target').agg('min') # min, max, sum, count
iris.groupby(['target','sepal length (cm)']).agg('min') # group by multiple features
iris.loc[:,['target','rank_sl']].groupby('target').agg('max')
iris.groupby(by='target')['sepal length (cm)'].value_counts() # by target, how many times sepal length = 8.3 in the column, how manuy times sepal length = 7.8 in the column and so on
iris.groupby(by='target').nunique() # by target distinct values across all columns. count (distinct cust_id) in SQL
#below 2 lines perform same operation as above line. Just that we are setting target as index and doing count(distinct) operation
iris.set_index('target', inplace=True)
iris.groupby(level='target').nunique() # level is used for index columns

df.groupby('col_A').get_group('A') # group by and using group key. output as below
#  CA  CB
#1 A 1
#2 B 2


In [ ]:
# SQL RANK
iris['rank_s1'] = iris['sepal length (cm)'].rank()
iris['rank_s1'] = iris['sepal length (cm)'].rank(method='max') # when there are ties. Default is average, min, max, first(similar to row no)
iris['rank_s1'] = iris['sepal length (cm)'].rank(method='dense', ascending = False) # similar to min, but ranks are continuous without gaps
iris['rank_s1'] = iris['sepal length (cm)'].rank(na_option = 'bottom')
iris['rank_s1'] = iris['sepal length (cm)'].rank(pct=True, ascending = False) # percentile
iris['target'].astype(int)

iris.groupby('target').cumcount()+1 # row number generated split by target.

In [ ]:
# SQL ORDER BY
iris.sort_values(by=['target'], ascending=False)
iris.sort_values(by=['target','sepal length (cm)'], ascending=[False,True])
iris.sort_values(by=['rank_s1'], ascending=True, inplace=True)
#usage of loc and iloc after sorting values (index will not be in order)
iris.loc[118:122,] # Select index value between 118 and 122 (prints 3 rows for this dataset, rank and orderby)
iris.iloc[118:122,] # Select position between 118 and 122 ( Prints 4 rows)
iris.loc[42:41,] # prints 4 rows for this dataset
iris.iloc[42:41,] # no output


In [ ]:
# SQL DELETE ROW AND COLUMN,  RENAME COLUMNS
del iris['rank_s1']
iris.drop(columns='rank_s1')
iris.drop(index = [x for x in range(1,50)]) # dropping rows
iris.drop(iris.index[0:50], inplace=True)
iris.rename(columns ={'rank_s1':'rank_','target':'target_new'})

In [ ]:
# INDEX FUNCTIONS
iris.set_index('rank_s1', inplace=True) # replace current index and have rank_s1 as index
iris.reset_index(inplace=True) # bring back rank_s1 as column and have increasing integers as index. drop=False is default
iris.reset_index(drop=True, inplace=True) # rank_s1 will be removed from dataframe, increasing integers will be in index
# Another usecase - If we drop some rows in between, reset index can be used to reset the index values
iris.sort_index(ascending=True, inplace=True) # sort index in ascending order
iris[iris.index] # Print index range - rangeindex

df1.swaplevel(0,1, axis=1).sort_index(axis=1) # only for hierarichal index, you can use to swap level

df.groupby('Company_Name')['Name'].nunique().sort_values(ascending=False)[0] # Value of first row
df.groupby('Company_Name')['Name'].nunique().sort_values(ascending=False).index # all index in an array
df.groupby('Company_Name')['Name'].nunique().sort_values(ascending=False).index[0] # value of first index

df.to string(index=false) # will remove index column while printing

In [ ]:
# HANDLING MISSING DATA
iris.dropna(how='any', inplace=True, axis=0) # drop if any value of a row is NaN, if how = 'all', then drop row if all values are NaN in a row.
iris['target'].dropna(how='any', inplace=True, axis=0)
iris.fillna(value='') # this can be used for data cleaning process
iris['target'].fillna(method='ffill') # value from the previous row in the column is filled in this cell, you can also set limit for this
iris['target'].fillna(method='ffill', limit=1) # Consider 2 NaN's simultaneously - only one NaN next to that will be filled with the above value
#similarly bfill, backfill, pad methods are used.


In [ ]:
# SUMMARIZE DATA
len(iris) # no of rows
iris['target'].value_counts() # a=50, b=50, c=50; {select target, count(*) from table group by 1} in SQL
iris['target'].nunique() # output is just 3, as we have a,b,c (above line example) ; count (distinct cust_id) in SQL
iris.describe()
iris.info()
iris.sum() # sum of values across all variables. what will happen for string columns ?
iris['target'].sum() # count(), median(), quantile(), min(), max(), var(), std(), mean()
iris.sum(axis=1) # column wise sum calculation, similarly we can use other agg functions
iris.abs() # absolute value
iris.target.mode()[0] # subscript is required here as mode will return series and not single value.

#swap rows
row_2, row_4 = df.iloc[1], df.iloc[3]
df.iloc[3] = row_2
df.iloc[1] = row_4

#replace
df.replace(1,2) # replace all 1 with 2
df.replace([1,5],[2,6]) # Replace all '1' with '2' and '5' with '6' in a single line of code

#sample
sf.sample(2, random_state=3)

# index max and min
iris['sepal length (cm)'].idxmax() # index max
iris['sepal length (cm)'].idxmin() # index min

iris.clip(lower=-10,upper=10, axis=1) # outlier capping for a column
iris.clip(lower=-10,upper=10) # all values below -10 to -10 & all values above 10 to 10. Horizontally, this is not outlier capping of a column
#we can also pass in a array for lower and upper limit and make it dynamic

iris.shift(-1) # shift at bottom
iris.tail()
iris.cummax() # current row and previous row is compared and max is calculated cummulatively
# similarly we have cummin(), cumprod(), cumsum()
# same functions can be used along with group by
iris.groupby('target').cumsum() # cumsum is calcualted split by target. EG: for all 0's it starts from begining and for 1's it starts again from begining
iris['sepal length (cm)'].quantile([0.25,0.5,0.75,1])

pd.DataFrame(iris.value_counts()) #{select @<all columns>, count(*) from table}
pd.DataFrame(iris.nunique()) #{select count(distinct col_1), count(distinct col_2)...., count(distinct col_n) from table}
pd.DataFrame(iris.groupby(by='target').value_counts()) # {select target, @<all columns>, count(*) from table group by target} target+all columns set to index
pd.DataFrame(iris.groupby(by='target').nunique()) # {select target, count(distinct col_1), count(distinct col_2)...., count(distinct col_n) from table group by target}
iris.groupby(by='target')['sepal length (cm)'].value_counts() # {select target, sepal_length, count(*) from table group by 1,2}
pd.DataFrame(iris.sum()) ##{select sum(col_1), sum(col_2)...., sum(col_n) from table}


In [ ]:
# RESHAPING DATA
iris_df = iris.copy()
melted_iris = pd.melt(iris_df) # all Columns into rows # name of the column will move under "variable" and the column data into "value"
pd.melt(iris_df, id_vars='target', value_vars='rank_s1', var_name='changed_variable', value_name='changed_value') # level of target will not be changed; rank_s1 alone will move to column

pd.pivot(melted_iris, columns='variable', values='value') # move dataset back to original structure, but while melting, the no of rows would have increased. If we pivot, the no of rows will not decrease, so filled with NaN
#also pivot can be used similar to excel pivot in the original dataset
#pivot_table is more powerful, overcomes shortcomings of pivot.
pivot_iris = pd.pivot_table(iris,
                      columns='target',
                      values=['sepal length (cm)','sepal width (cm)'],
                            aggfunc='count')
pivot_iris # values are aggregated (mean) by default
# if index has duplications and cannot be reshaped(pivoted/melted), then throws error

pd.concat([iris,iris_df],ignore_index=False, axis=0, keys=['key1','key2']) # keys will be created as another index, so ignore_index should be False, else second index is not created, also wont throw any error
pd.concat([iris,iris_df],ignore_index=True) # rewrite index with increasing numbers for both (either row or column)

iris.stack() # works similar to melt, but melt creates "variable" as column, but stack creates as a index.
iris.unstack() # unstacking the stacked dataset


In [ ]:
# MAKE NEW COLUMNS
iris_new = iris.assign(slm= iris['sepal length (cm)']*2,
                       slm2 = iris['sepal length (cm)']*3) # new column slm & slm2 is created

iris['slm_cut'] = pd.cut(iris.target, bins=3, right=True, labels=['a','b','c']) # if right=True, then upper bound close ended. It will be rounded off
iris['slm_cut'] = pd.cut(iris.target, bins=3, right=False, labels=False) # if labels=False, it assigns numbers from 0
iris['slm_cut'] = pd.cut(iris.target, bins=[0,1,2,3], right=False, labels=False)
iris['slm_cut'] = pd.cut(iris['sepal length (cm)'], bins=5, right=False, labels=False)

iris['slm_cut'] = pd.qcut(iris['sepal length (cm)'], q=5, labels=False) # qcut- quantile cut. looks into data and split into 3 quantiles ( equal splits)
iris.head()

In [ ]:
# COMBINE DATASETS
pd.merge(iris, iris_df, how='inner', on='target')
pd.merge(iris, iris_df, how='left', on='target')
pd.merge(iris, iris_df, how='right', on='target')
pd.merge(iris, iris_df, how='outer', on='target')
pd.merge(df1,df2,how='outer',on='col_A', indicator=True) # source of each row form indicator parameter


df1.join(df2, on ='col_A') # similar to above merge
# df2 uses index to join, df1 uses col to join. if the col is string and index is int, throws error. reindex before join required.

In [ ]:
# STRING METHODS
xx = iris['str_col']
type(xx) # returns a series
yy = iris.str_col
type(yy) # yy is a string, if all values in a column is same. If not returns a series (same as above)
iris['str_col'] = 'Santhosh Kumar Mohan'

iris['str_col'].str # converted as strings from series <Pandas.core.strings.accessor.stringmethods>, but remain as a series/DF if any str functions applied.
iris['str_col'].str.lower() # after converting, making lower case - o/p converted to series/df
iris.str_col.lower() # lower case is directly applied as it is already a string. look for yy example above
iris.str_col.casefold() # same as above, but it peforms strict sting comparision. EG: Converts data from german to english

iris['str_col'].str.capitalize() # first name first letter will be capital, second name first letter will be small and soon
iris['str_col'].str.title() # first name first letter will be capital, second name first letter will be capital and soon
iris['str_col'].str.upper() # all to upper case
iris['str_col'].str.swapcase() # as the name says, all upper to lower and viceversa
iris['str_col'].str.strip() # all leading and trailing whitespaces are removed
iris['str_col'].str.strip('San') # remove "San" from "Santhosh Kumar Mohan"
iris['str_col'].str.strip('Kumar') # nothing happens, prints "Santhosh Kumar Mohan"

iris['str_col'].str.startswith('San') # return T/F
iris['str_col'].str.endswith('han') # return T/F

iris['str_col'].str.index('z') # error as substring not found
iris['str_col'].str.find('z') # similar to above, but no error. Prints "-1" is not found
iris['str_col'].str.index('Mohan') # position of the starting letter. If repeated char, then position of first occurance
iris['str_col'].str.find('Mohan') # same output as above

iris['str_col'].str.center(22,'#') # add # in the front and then at back # default is white space
iris['str_col'].str.center(10,'#') # Prints entire name
iris['str_col'].str.count('a') # counts number of 'a' in the string
iris['str_col'].str.count('a',1,5) # no of "a" in the string between position 1 to 5

iris['str_col'].str.isalpha() # return T/F if value is alphabet
iris['str_col'].str.isdecimal() # return T/F if value is decimal
iris['str_col'].str.isalnum() # return T/F if value is alphanumeric
iris['str_col'].str.isdigit() # return T/F if value is digit
iris['str_col'].str.isnumeric() # return T/F if value is numeric
iris['str_col'].str.isidentifier() # return T/F if value is identifier # not to start with numbers, shouldnt have space in the string etc.
iris['str_col'].str.islower() # return T/F if value is lower case
iris['str_col'].str.isupper() # return T/F if value is upper case
iris['str_col'].str.istitle() # return T/F if value is title case

iris['str_col'].str.partition(" ") # splits into 3 sections, before, partition value, after - "Santhosh" " "Kumar Mohan"

In [ ]:
iris[iris.target.isin(iris_df.target)] # only IRIS dataset will be displayed based on the matching condition
iris[~iris.target.isin(iris_df.target)]

# PLOTTING
iris['sepal length (cm)'].plot.hist()
iris.plot.scatter(x='sepal length (cm)', y='sepal width (cm)')

iris.count() # no of non-NaN cells
iris.isna().sum() # no of NAN cells # returns column name and sum of True's
iris.columns.isna() #any of the columns has NaN - returns array of T/F

In [ ]:
# INSERT COLUMN AND ROW IN A LOCATION
# insert column
list_val = [1,2,3,4]
new_df = df.insert(loc=2, column='col_2', value=list_val)

# one hot encoding
pd.get_dummies(iris.target, prefix='var')

#no of rows and columns
df.shape[0] # rows
df.shape[1] #columns




In [ ]:
# ADD PREFIX AND SUFFIX DATA
#inbuilt functions are available to add prefix and suffix to the dataset or column names

#add prefix to the col names

df.columns = 'col_' + str(column) for column in df.columns


#**`SEABORN PYTHON `**

In [ ]:
# line plot
sns.lineplot(iris,x='sepal length (cm)',y='sepal width (cm)')
sns.lineplot(iris,x='sepal length (cm)',y='sepal width (cm)',hue='target') # data split by hue
# scatter plot
sns.scatterplot(iris,x='sepal length (cm)',y='sepal width (cm)')
sns.scatterplot(iris,x='sepal length (cm)',y='sepal width (cm)',hue='target') # data split by hue
# histogram
sns.histplot(iris, x='sepal length (cm)') # no y axis as histogram gives count by  X axis
sns.histplot(iris, x='sepal length (cm)', hue='target')
# PDF
sns.kdeplot(iris,x='sepal length (cm)') # note the key work kdeplot for PDF function
sns.kdeplot(iris,x='sepal length (cm)',hue='target')
# box plot
sns.boxplot(iris,x='sepal length (cm)')
sns.boxplot(iris,y='sepal length (cm)')
sns.boxplot(iris,y='sepal length (cm)', x='target')
# violin plot
sns.violinplot(iris,y='sepal length (cm)') # on top of box, this gives data density
sns.violinplot(iris,y='sepal length (cm)', x='target') # make sure segment feature should be in x
# pair plot
sns.pairplot(iris)
sns.pairplot(iris, hue='target')
# heat map
sns.heatmap(iris.corr(),annot=True, cmap='GnBu')
# joint plot
sns.jointplot(iris,x='sepal length (cm)', y='sepal width (cm)')
sns.jointplot(iris,x='sepal length (cm)', y='sepal width (cm)', hue='target')

#**`SPECIAL FUNCTIONS`**

In [ ]:
# OTHER FUNCTIONS

# map categorical to integer values
df = pd.DataFrame([["A", 1], ["B", 2],
                   ["A", 3], ["D", 4]],
                  columns=["col_A", "col_B"])

new_df = df.col_A.astype('category').cat.codes # new random integer codes assingned to col_A
# if it is ordered, you can use parameter ordered=True to have integer codes in ordered manner
# this is useful in feature engineering works

#reverse dataframe row wise
df[::-1] # reverse rows ( axis = 0)
df[df.columns[::-1]] # reverse columns ( axis = 1)

# split dataframe
dt = np.array_split(df,2) # split the dataframe into 2 no of parts
dt[0]. dt[1] # first part and second part

l=[1,2,3,4,5,6,7,8]
l.pop() # 2 operations are done, 1.removes last element from the list inplace=true, 2.returns last element as output
l.pop(2) # removes "3" from the list and returns "3" as output

# APPLY

def multiply(x):
  x = x+2
  return x

iris['sepal length (cm) new'] = iris['sepal length (cm)'].apply(multiply) # only the column changes
iris.head()

iris=iris.apply(multiply) # entire dataset is updated
iris.head()

iris=iris+2 # same output as above
iris.head()
#apply function is used, if you want to create a user defined function instead of inbuilt functions in python

# APPLYMAP
iris=iris.applymap(multiply) # OUTPUT IS SAME AS ABOVE, BUT APPLYMAP IS ALWAYS APPLIED TO ENTIRE DATASET, ELEMENT WISE
iris.head()

# MAP
pd.map({'cat':'kitten', 'dog':'puppy'}) # easy changing of values in a dataset, change cat to kitten and do to puppy
# cons: map turns value to NaN, if we give replacement in dict above. EG: dataset has rabbit, but we didnt give change in name for rabbit, so map turns rabbit to NaN.

iris.map({0:-1,1:-2,2:-3}, na_option='ignore') # na_option can be applied for applymap & apply as well

In [ ]:
# ENUMERATE FUNCTION

alpha = ['a','b','c','d']
for count,value in alpha:
  print(count,value) #ERROR
for count,value in enumerate(alpha, start=1): # enumerate is an unpacking method, start=1(index starts from 1)
  print(count,value)

In [ ]:
# LAMBDA FUNCTION

add = lambda x,y:x+y # x,y are the input variables for the function # lambda should be one liner function
add(4,5) # output = 9

nos = 2
func = lambda x: x**2
func(nos) # output is 4

nos = [3,4,5]
nos*2 # extends the list output = [3,4,5,3,4,5]

func = lambda x: x**2
func(nos) # THROWS ERROR

def my_map(my_func, my_iter):
  result=[]
  for item in my_iter:
    new = my_func(item)
    result.append(new)
  return result
nos = [3,4,5]
new_nos = my_map(lambda x:x**2, nos)
print(new_nos)

In [ ]:
# zip function - it is used to combine iterables

names = ['santhosh','kumar','mohan']
ages=[23,34,36]
intials = ['er','ty','ui']
z = zip(names, ages)
for i,j in z:
  print(i)
  print(j)


In [ ]:
#empty, item, any, all

import pandas as pd
data = {
  "firstname": ["Sally", "Mary", "John"],
  "age": [50, 40, 30]}
df = pd.DataFrame(data)
for x, y in df.items():
  print(x)
  print(y)


iris.isna().any() # True, if any one is true # False for empty set
iris.isna().all() # True, if all the values are true # True for empty set


In [ ]:
#EXAMPLES
#GroupBy col_A, then compute a new column as (10*col_B/col_C) - DEEPNOTE - AWI CHAWLA

import pandas as pd
df = pd.DataFrame([[4, 1, 5],
                   [5, 5, 1],
                   [1, 9, 3],
                   [8, 5, 8]],
                  columns=["col_A", "col_B", "col_C"])


def func(group):
    return (10*group.col_B/group.col_C).mean()

new_df = df.groupby('col_A').apply(func)
print(new_df)



#**` LIST COMPREHENSION`**

In [ ]:
# LIST COMPREHENSION
# EG1 : fruits = ['apples','oranges','grapes'] do to upper
fruits = ['apples','oranges','grapes']
fruits_new = [fruit.upper() for fruit in fruits]
print(fruits)
print(fruits_new)

# bits = [1,0,0,0,1] change to T/F
bits = [1,0,0,0,1]
bits_new = ['True' if bit == 1 else 'False' for bit in bits]
print(bits)
print(bits_new)

# my_string = 'HelloMyNameIsSanthosh' space between words
my_string = "HelloMyNameIsSanthosh"
print(my_string)
new_string = "".join([i if i.islower() else " "+i for i in my_string])[1:]
print(new_string)[ ]


#**`LEARNING NUMPY`**

In [ ]:
import numpy as np
# creating array 1D
a= np.array([1,2])
print(a)
# creating array 2D
b= np.array([(1,9,3),(7,5,6)])
print(b)
# creating array 3D
c= np.array([[(9,1,9),(7,4,6)],[(1,2,3),(6,4,5)],[(1,2,3),(5,4,6)]])
print(c)

# All array values should come within []
# 3D array method can be remembered as (Height, Length, Breadth). Stacking up plates on top.
# (2,1,3) & (3,2,3) arrays cannot be added as the axis 1 and axis 2 should match to join/combine/agg two arrays.

[1 2]
[[1 9 3]
 [7 5 6]]
[[[9 1 9]
  [7 4 6]]

 [[1 2 3]
  [6 4 5]]

 [[1 2 3]
  [5 4 6]]]


In [ ]:
# Initial placeholders
x=np.zeros((3,4)) # array of all zeros
x=np.ones((3,4),dtype=float) # array of all ones
x=np.empty((3,2)) # unlike zeros, this doesnt set values to 0, so marginally faster.
x=np.full((2,2),3) # 2X2 array with all values as 3

y=np.arange(10,55,5) # creates 1D array starting from 10 to 55 with difference of 5
y=np.linspace(10,55,5) # 1D array of size 5, evenly spaced between 10 to 55 # [10.   21.25 32.5  43.75 55.  ]
y=np.eye(4) # 4X4 identity matrix # Diagnal to be 1 and rest all zero

np.linspace(2,3,10) # range from 2 to 3, 10 values equal spaced
np.arange(2,11,2) # range from 2 to 11, incremental of 2 from start value
np.identity(2, dtype='float') # identity matrix with 1 in columns

# integer random values
np.random.randint() # ERROR, need atleast one value
np.random.randint(100) # random no bw 0 to 100
np.random.randint(3,100) # random number between 3 to 100
np.random.randint(3,100, size=(3,4)) # random number b/w 3 to 100 of matrix size 3x4
# float random values
np.random.rand() # one random float value b/w 0 to 1
np.random.rand(2) # two random float value b/w 0 to 1 - 1D array
np.random.rand(3,4) # random values of 3x4 matrix between 0 to 1 - 2D array
# using choice for random
np.random.choice([3,5,7,9]) # return one value from the choice list
np.random.choice([3,5,7,9], size=(3,4)) # 3x4 matrix with random values from the choice list





In [ ]:
# Inspecting array
len(c) # length of array # NOTE : len is not an attribute
c.size # total entries (2,3,2) array, output will be 12
c.shape # (2,1,2) which explains dimension of array
c.ndim # no of array dimensions

c.dtype # data type
c.dtype.name # data type - almost same output as above
n=c.astype(float) # datatype of array c is not overwritten, so creating a new array to have converted float values
n.dtype # output will be float

# Copy array
h=c.view() # view is not a copy, any changes made to h will affect c
h=c.copy() # h is a copy and any changes made to h will NOT affect c


In [ ]:
# different data types
np.int64
np.float32
np.complex # complex no's 128 float
np.bool # True false values
np.unicode_ # Fixed length unicode type
np.string_ # Fixzed length string type
np.object # python object


In [ ]:
# Arithmetic operations

a+b # Addition # Arrays of different shapes cannot perform arithmetic operation.
# (2,3) array + (2,2,3) array can be added up.
# (2,2) array + (2,2,3) array CANNOT be added up
# same applies for all other aritmetic operations which involve 2 arrays.
a-b # Subtraction
a*b # Multiplication
a/b # Division
np.exp(b) # Exponentiation
np.sqrt(c) # Square root

b @ a # same as dot
np.matmul(a,b) # same as dot
np.dot(a,b) # Dot product
np.einsum('ij,ij->i', a, b) # row wise dot product
np.einsum('ij,ij->j', a, b) # column wise dot product


# b.dot(a) - the final output array size will match the array size of a.
# 3X3 .dot(3X2) - "7" method of multiplication is done.
# 3X2 .dot(3X2) - this will throw error

In [ ]:
# Comparison
b==c # This will return an array of true/false. if the shape of array b & c is not comparable, then it will throw error.
c<20 # return an array of True/False
np.array_equal(f,c) # Compares each values in array f & c, if all matches then TRUE, else FALSE - TREUE/FALSE will be returned as single value and not as array elements
np.dia(a) # print diagonal


In [ ]:
# Aggregate functions
c.sum()
c.min()
c.max()

c.sum(axis=0)
c.sum(axis=2)

print(c)
f=c.cumsum() # creates cumsum with 1D array as output
print(f)
c.std() # std
c.mean() # mean across all values in array
np.median(c) # note the syntax difference

In [ ]:
# sorting
b.sort() # general sort on axis=1 (row) 2D array
b.sort(axis=0) # sort on axis=0 (column) 2D array
c.sort() # general sort on axis = 2 (row) 3D array
c.sort(axis=1) # sort on axis = 1 (column) 3D array
c.sort(axis=0) # sort on axis = 0 (height) 3D array

a = np.array([3, 1, 2])
np.argsort(a) # after sorting, what would be the order of indices -> that gets printed
# output = [1,2,0]

a = np.array([[3, 0, 0], [0, 4, 0], [5, 6, 0]])
non_zero_ind = np.nonzero(a) # this gives a tuple of arrays, unreadable format - Prints indexes of non zero elements
print(np.transpose(non_zero_ind)) # convert to a readable format
a[np.nonzero(a)] #print non zero elements


In [ ]:
# For subsetting and slicing, think 3D array as a layer
# Subsetting

print(c)
#c[0]
c[1,0,1]

# Slicing
print(c[0:2])
print(c)
#print(c[0:2,1,2]) # Final result will be 1D array. 0:2 - this will take values of Position (0,1)
print(c[0:2,1,0:2]) # Final result will be 2D array.
print(c)
#c[1,:,2] # sections, rows, columns
x=c[:,:,-1]
x.shape
# Boolean indexing
c[c<4] # new 1D array with values of c<4
c<4 # array of T/F condition

In [ ]:
# Array manipulation
i=np.transpose(c) # 3X2 matrix will be transformed to 2X3 matrix
c.T # performs same operation as above

v=c.ravel() #Flatten the array
c.reshape(6,3,1) # eg: if 18 elements in array, you can reshape to any type of matrix

# Combining arrays
np.insert(b,1,13) # Insert 13 at 1st position # if b is 2D/3D array, after inserting, gets converted to 1D array # Original b or c array doesnt get updated, will get create it as a new array
np.delete(b,1) # delete the value in 1st position
np.delete(b,[1]) # performs same operation as above
np.append(b,c) # append values of array c behind array b # o/p will be 1D array

np.vstack((b,b)) # Stack arrays vertically ( append/Join as rows)
np.concatenate((b,b)) # Performs same as above
np.r_[b,b] # Performs same as above

np.hstack((b,b)) # Stack arrays horizontally ( append/Join as columns)
np.concatenate((b,b),axis = 1) # Performs same as above
np.c_[b,b] # Performs same as above

# Splitting arrays
np.hsplit(b,1)
np.vsplit(c,1)

In [ ]:
np.unique(a) # unique values in a
np.unique(a, axis=0) # unique rows
np.unique(a, axis=1) # unique columns

np.squeeze(a) # returns single 1D array


#**`Questions from Krish Naik`**

In [ ]:
import pandas as pd
import numpy as np

# REVERSE A STRING
string = 'Santhosh'
string[::-1]

# PALINDROME
def palindrome(string):
  if(string == string[::-1]):
    print("String is a Palindrome")
  else:
    print("string is not a Palindrome")

palindrome(input("Enter a string : "))

# FACTORIAL OF A NUMBER
def factorial(num):
  x = 1
  for n in range(1,num+1):
    x *= n
  return x
fact = factorial(int(input("Enter the number you want to calculate factorial : ")))
print(fact)

# FIBONACCI SERIES
def fibonacci(num):
  x, y, z = 0,1,0
  arr = []
  for n in range(0,num):
    z = y
    y = x + z
    xx = [x]
    arr.append(xx)
    x = z
  return arr
fibo = fibonacci(int(input("Enter number of fibonacci required : ")))
print(fibo)



Enter number of fibonacci required : 10
[[0], [1], [1], [2], [3], [5], [8], [13], [21], [34]]


In [147]:
# Machine learning plus

import pandas as pd
import numpy as np
from google.colab import data_table
data_table.enable_dataframe_formatter()
pd.__version__

list = [1,2,3,4]
type(list)


mylist = list('abcdefghijklmnopqrstuvwxyz')
type(mylist)
arr = np.arange(26)
mydict = dict(zip(mylist, arr))
sr = pd.Series(mydict)
df = sr.to_frame().reset_index()
df.rename(columns = {'index':'col1',0:'col2'}, inplace=True)

df1 = pd.Series(mylist)
df1 = df1.to_frame().reset_index(drop=True).rename(columns = {0:'col3'})

ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))
ser1.name = 'Alphabets'
ser2.name = 'Numbers'
df = pd.concat([ ser1.to_frame(),ser2.to_frame()], axis=1)

df.name = 'Alpha-Numerical'
df.head()

ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])
ser1[~ser1.isin(ser2)]
ser1.name='col1'
ser2.name='col1'
pd.merge(ser1,ser2, how='outer')[~pd.merge(ser1,ser2, how='outer').isin(pd.merge(ser1,ser2, how='inner').col1.values)].col1.dropna()

ser = pd.Series(np.random.normal(10, 5, 25))
ser = ser.to_frame().rename(columns={0:'col1'})
ser['pct'] = ser['col1'].rank(pct=True, ascending=True)
ser = ser.sort_values(['pct'], ascending=True).reset_index(drop=True)
ser[ser['pct']<0.25]

np.percentile(ser, q=[0,25,50,75,100])

ser = pd.Series(np.random.randint(1, 5, 12))
ser = ser.to_frame().rename(columns = {0:'col1'})
ser.groupby('col1').count()

Empty DataFrame
Columns: []
Index: [1, 3, 4]

In [ ]:
import pandas as pd
import numpy as np
from sklearn import datasets
dir(datasets)

df = datasets.fetch_california_housing()
ch = pd.DataFrame(data=df.data,columns=df.feature_names)
ch.head()
ch['target'] = df.target
ch.dtypes

ch.groupby(['HouseAge','AveRooms'])['Population','target'].sum()

# Calculate the average income of households in each neighborhood and determine the neighborhood
# with the highest average income.



In [34]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.datasets import load_iris


iris = load_iris()
X = iris.data
y = iris.target

X_2d = X[:, :2]
X_2d = X_2d[y > 0]
y_2d = y[y > 0]
y_2d -= 1

X_2d.shape
y_2d.shape

x=np.logspace(15, 20, 23)
sns.lineplot(x,markers=True)

<Axes: >

In [43]:
from sklearn.model_selection import StratifiedShuffleSplit
cv = StratifiedShuffleSplit(n_splits=5, test_size=0.1, random_state=0)

for train_index, test_index in cv.split(X, y):
  print(test_index)

[ 55  44  50  46 103   3  47  99  86 129   0 100 136 134  88]
[  9  25 124 145 104  65  50  29  97 116 123  61  46  21  58]
[  5 101  74  90  53 128  37 142  28  38 120 116  55  86  45]
[145  37 131  41  58 125  29 106  52  88 133  60  40  17  55]
[ 85  99 102  88  34 101  31 113 119  17  29  80  86  28 128]


In [57]:
f1 = np.arange(20)
#f2 = np.exp(f1)
#f3 = np.log(f1)
f4 = f1**2
sns.lineplot(f1)
sns.lineplot(f2)
#sns.lineplot(f3)
sns.lineplot(f4)

<Axes: >

In [12]:
from sklearn import svm
X = [[0, 3], [2, 5]]
y = [0, 1]
clf = svm.SVC(kernel='linear')
clf.fit(X, y)
x_test = [[1,2],[1,4]]
clf.predict(x_test)

clf = svm.LinearSVC()
clf.fit(X, y)
x_test = [[1,2],[1,4]]
clf.predict(x_test)


X = [[0], [1], [2], [3]]
Y = [0, 1, 2, 3]
x_test = [[2]]
clf = svm.SVC(decision_function_shape='ovo')
clf.fit(X, Y)
clf.predict(x_test)


dec = clf.decision_function([[1]])
dec.shape[1]
clf.decision_function_shape = "ovr"
dec = clf.decision_function([[1]])
dec.shape[1] # 4 classes


array([2])

In [24]:
from sklearn.linear_model import Lasso
import numpy as np
n_samples, n_features = 10, 5
rng = np.random.RandomState(0)
y = rng.randn(n_samples)
X = rng.randn(n_samples, n_features)

clf = Lasso(alpha=0.6)
clf.fit(X, y)
lasso_coe = clf.predict(X)

print(clf.predict(X))
print(np.dot(X,clf.coef_) + clf.intercept_)

[0.73802317 0.73802317 0.73802317 0.73802317 0.73802317 0.73802317
 0.73802317 0.73802317 0.73802317 0.73802317]
[0.73802317 0.73802317 0.73802317 0.73802317 0.73802317 0.73802317
 0.73802317 0.73802317 0.73802317 0.73802317]


In [18]:
from sklearn.linear_model import Ridge
import numpy as np
n_samples, n_features = 10, 5
rng = np.random.RandomState(0)
y = rng.randn(n_samples)
X = rng.randn(n_samples, n_features)

clf = Ridge(alpha=1.0)
clf.fit(X, y)
ridge_coe = clf.predict(X)

print(clf.predict(X))
print(np.dot(X,clf.coef_) + clf.intercept_)

[ 0.95424223  0.48712089  1.10388121  1.79105759  1.05769745 -0.07915715
  1.12314109 -0.22941441  0.64906337  0.52259943]
[ 0.95424223  0.48712089  1.10388121  1.79105759  1.05769745 -0.07915715
  1.12314109 -0.22941441  0.64906337  0.52259943]


In [19]:
from sklearn.linear_model import LinearRegression
import numpy as np
n_samples, n_features = 10, 5
rng = np.random.RandomState(0)
y = rng.randn(n_samples)
X = rng.randn(n_samples, n_features)

clf = LinearRegression()
clf.fit(X, y)
lr_coe = clf.predict(X)

print(clf.predict(X))
print(np.dot(X,clf.coef_) + clf.intercept_)

[ 1.40977378  0.05327317  0.87351204  2.3979991   1.72087882 -0.6431204
  0.88107802 -0.51570968  0.28830167  0.91424518]
[ 1.40977378  0.05327317  0.87351204  2.3979991   1.72087882 -0.6431204
  0.88107802 -0.51570968  0.28830167  0.91424518]


In [21]:
print(ridge_coe.sum())
print(lr_coe.sum())

7.380231707288346
7.380231707288347
